import { colors } from '@/constants/colors';
import { StyleSheet } from 'react-native';

export const dashboardScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorder,
    overflow: 'hidden',
    position: 'relative',
  },
  headerButtons: {
    position: 'absolute',
    top: 16,
    left: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    zIndex: 10,
  },
  languageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.whiteTint30,
  },
  languageText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  headerContent: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 16,
  },
  avatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  avatarGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: colors.background,
  },
  headerText: {
    flex: 1,
    alignItems: 'flex-end',
  },
  greeting: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 4,
  },
  creditsRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  creditsButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
  },
  creditsText: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  modeToggleContainer: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  modeToggle: {
    flexDirection: 'row-reverse',
    borderRadius: 16,
    padding: 4,
    gap: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.glassBorder,
  },
  modeButton: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    position: 'relative',
  },
  modeButtonActive: {
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  modeButtonGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 12,
  },
  modeButtonText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: colors.textMuted,
    zIndex: 1,
  },
  modeButtonTextActive: {
    color: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingTop: 0,
  },
  statsRow: {
    flexDirection: 'row-reverse',
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    borderRadius: 24,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 12,
  },
  statCardPrimary: {},
  statCardGradient: {
    padding: 20,
  },
  statCardBlur: {
    flex: 1,
    padding: 20,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.glassBackgroundStrong,
  },
  statIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.whiteTint20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  statIconSecondary: {
    backgroundColor: colors.statIconSecondaryBg,
  },
  statValue: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: colors.background,
    marginBottom: 4,
    textAlign: 'right',
  },
  statLabel: {
    fontSize: 14,
    color: colors.whiteOnAccent,
    textAlign: 'right',
    fontWeight: '500' as const,
  },
  statValueSecondary: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 4,
    textAlign: 'right',
  },
  statLabelSecondary: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'right',
    fontWeight: '500' as const,
  },
  creditsBanner: {
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 16,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
  },
  creditsBannerGradient: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    padding: 20,
    gap: 16,
  },
  creditsBannerContent: {
    flex: 1,
    alignItems: 'flex-end',
  },
  creditsBannerTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.background,
    marginBottom: 2,
  },
  creditsBannerSubtitle: {
    fontSize: 14,
    color: colors.whiteOnAccent,
  },
  createTenderCTA: {
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 24,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  ctaGradient: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    padding: 24,
    gap: 16,
  },
  ctaIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.whiteTint20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaContent: {
    flex: 1,
    alignItems: 'flex-end',
  },
  ctaTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    color: colors.background,
    marginBottom: 4,
  },
  ctaSubtitle: {
    fontSize: 14,
    color: colors.whiteOnAccent,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 16,
    textAlign: 'right',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: colors.textMuted,
    marginTop: 16,
    marginBottom: 4,
    textAlign: 'center',
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: colors.muted,
    textAlign: 'center',
  },
  tenderCard: {
    backgroundColor: colors.glassBackground,
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    borderWidth: 1,
    borderColor: colors.glassBackgroundStrong,
  },
  tenderCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  tenderHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  tenderTitle: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: colors.text,
    flex: 1,
    marginRight: 8,
    textAlign: 'right',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  organizerInfo: {
    marginBottom: 12,
  },
  organizerText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'right',
  },
  tenderDetails: {
    gap: 8,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  detailText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  payText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.successDark,
  },
  pendingIndicator: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.glassBorder,
    alignItems: 'center',
  },
  pendingText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.warning,
  },
  progressSection: {
    marginTop: 4,
  },
  progressHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressLabel: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  progressCount: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
  },
  progressBar: {
    height: 8,
    backgroundColor: colors.border,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
});
